// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video.proto

package com.xty.dubbo_gen.video;

/**
 * Protobuf type {@code douyin.core.FeedRequest}
 */
public final class FeedRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:douyin.core.FeedRequest)
    FeedRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FeedRequest.newBuilder() to construct.
  private FeedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FeedRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FeedRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_FeedRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_FeedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xty.dubbo_gen.video.FeedRequest.class, com.xty.dubbo_gen.video.FeedRequest.Builder.class);
  }

  public static final int LATEST_TIME_FIELD_NUMBER = 1;
  private long latestTime_ = 0L;
  /**
   * <pre>
   * 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
   * </pre>
   *
   * <code>int64 latest_time = 1;</code>
   * @return The latestTime.
   */
  @java.lang.Override
  public long getLatestTime() {
    return latestTime_;
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private long userId_ = 0L;
  /**
   * <pre>
   * 可选参数，登录用户设置
   * </pre>
   *
   * <code>int64 user_id = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (latestTime_ != 0L) {
      output.writeInt64(1, latestTime_);
    }
    if (userId_ != 0L) {
      output.writeInt64(2, userId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (latestTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, latestTime_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, userId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xty.dubbo_gen.video.FeedRequest)) {
      return super.equals(obj);
    }
    com.xty.dubbo_gen.video.FeedRequest other = (com.xty.dubbo_gen.video.FeedRequest) obj;

    if (getLatestTime()
        != other.getLatestTime()) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LATEST_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLatestTime());
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xty.dubbo_gen.video.FeedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xty.dubbo_gen.video.FeedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xty.dubbo_gen.video.FeedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xty.dubbo_gen.video.FeedRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code douyin.core.FeedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:douyin.core.FeedRequest)
      com.xty.dubbo_gen.video.FeedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_FeedRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_FeedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xty.dubbo_gen.video.FeedRequest.class, com.xty.dubbo_gen.video.FeedRequest.Builder.class);
    }

    // Construct using com.xty.dubbo_gen.video.FeedRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      latestTime_ = 0L;
      userId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_FeedRequest_descriptor;
    }

    @java.lang.Override
    public com.xty.dubbo_gen.video.FeedRequest getDefaultInstanceForType() {
      return com.xty.dubbo_gen.video.FeedRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.xty.dubbo_gen.video.FeedRequest build() {
      com.xty.dubbo_gen.video.FeedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xty.dubbo_gen.video.FeedRequest buildPartial() {
      com.xty.dubbo_gen.video.FeedRequest result = new com.xty.dubbo_gen.video.FeedRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xty.dubbo_gen.video.FeedRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.latestTime_ = latestTime_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userId_ = userId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xty.dubbo_gen.video.FeedRequest) {
        return mergeFrom((com.xty.dubbo_gen.video.FeedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xty.dubbo_gen.video.FeedRequest other) {
      if (other == com.xty.dubbo_gen.video.FeedRequest.getDefaultInstance()) return this;
      if (other.getLatestTime() != 0L) {
        setLatestTime(other.getLatestTime());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              latestTime_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long latestTime_ ;
    /**
     * <pre>
     * 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
     * </pre>
     *
     * <code>int64 latest_time = 1;</code>
     * @return The latestTime.
     */
    @java.lang.Override
    public long getLatestTime() {
      return latestTime_;
    }
    /**
     * <pre>
     * 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
     * </pre>
     *
     * <code>int64 latest_time = 1;</code>
     * @param value The latestTime to set.
     * @return This builder for chaining.
     */
    public Builder setLatestTime(long value) {

      latestTime_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
     * </pre>
     *
     * <code>int64 latest_time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatestTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      latestTime_ = 0L;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <pre>
     * 可选参数，登录用户设置
     * </pre>
     *
     * <code>int64 user_id = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * 可选参数，登录用户设置
     * </pre>
     *
     * <code>int64 user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 可选参数，登录用户设置
     * </pre>
     *
     * <code>int64 user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:douyin.core.FeedRequest)
  }

  // @@protoc_insertion_point(class_scope:douyin.core.FeedRequest)
  private static final com.xty.dubbo_gen.video.FeedRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xty.dubbo_gen.video.FeedRequest();
  }

  public static com.xty.dubbo_gen.video.FeedRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FeedRequest>
      PARSER = new com.google.protobuf.AbstractParser<FeedRequest>() {
    @java.lang.Override
    public FeedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FeedRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FeedRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xty.dubbo_gen.video.FeedRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

