// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video.proto

package com.xty.dubbo_gen.video;

public interface FeedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.core.FeedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
   * </pre>
   *
   * <code>int64 latest_time = 1;</code>
   * @return The latestTime.
   */
  long getLatestTime();

  /**
   * <pre>
   * 可选参数，登录用户设置
   * </pre>
   *
   * <code>int64 user_id = 2;</code>
   * @return The userId.
   */
  long getUserId();
}
