// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video.proto

package com.xty.dubbo_gen.video;

public interface GetWorkCountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.core.GetWorkCountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
