// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video.proto

package com.xty.dubbo_gen.video;

public interface GetWorkCountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.core.GetWorkCountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 作品数量
   * </pre>
   *
   * <code>int64 work_count = 1;</code>
   * @return The workCount.
   */
  long getWorkCount();
}
