// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video.proto

package com.xty.dubbo_gen.video;

public interface PublishListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.core.PublishListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 状态码，0-成功，其他值-失败
   * </pre>
   *
   * <code>int32 status_code = 1;</code>
   * @return The statusCode.
   */
  int getStatusCode();

  /**
   * <pre>
   * 返回状态描述
   * </pre>
   *
   * <code>string status_msg = 2;</code>
   * @return The statusMsg.
   */
  java.lang.String getStatusMsg();
  /**
   * <pre>
   * 返回状态描述
   * </pre>
   *
   * <code>string status_msg = 2;</code>
   * @return The bytes for statusMsg.
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();

  /**
   * <pre>
   * 用户发布的视频列表
   * </pre>
   *
   * <code>repeated .douyin.core.Video video_list = 3;</code>
   */
  java.util.List<com.xty.dubbo_gen.video.Video> 
      getVideoListList();
  /**
   * <pre>
   * 用户发布的视频列表
   * </pre>
   *
   * <code>repeated .douyin.core.Video video_list = 3;</code>
   */
  com.xty.dubbo_gen.video.Video getVideoList(int index);
  /**
   * <pre>
   * 用户发布的视频列表
   * </pre>
   *
   * <code>repeated .douyin.core.Video video_list = 3;</code>
   */
  int getVideoListCount();
  /**
   * <pre>
   * 用户发布的视频列表
   * </pre>
   *
   * <code>repeated .douyin.core.Video video_list = 3;</code>
   */
  java.util.List<? extends com.xty.dubbo_gen.video.VideoOrBuilder> 
      getVideoListOrBuilderList();
  /**
   * <pre>
   * 用户发布的视频列表
   * </pre>
   *
   * <code>repeated .douyin.core.Video video_list = 3;</code>
   */
  com.xty.dubbo_gen.video.VideoOrBuilder getVideoListOrBuilder(
      int index);
}
