// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video.proto

package com.xty.dubbo_gen.video;

public interface PublishListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.core.PublishListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 访问用户id
   * </pre>
   *
   * <code>int64 from_user_id = 1;</code>
   * @return The fromUserId.
   */
  long getFromUserId();

  /**
   * <pre>
   * 被访问用户id
   * </pre>
   *
   * <code>int64 to_user_id = 2;</code>
   * @return The toUserId.
   */
  long getToUserId();
}
