// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video.proto

package com.xty.dubbo_gen.video;

public final class VideoServiceProto {
  private VideoServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_FeedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_FeedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_FeedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_FeedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_PublishActionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_PublishActionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_PublishActionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_PublishActionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_PublishListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_PublishListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_PublishListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_PublishListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_GetWorkCountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_GetWorkCountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_GetWorkCountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_GetWorkCountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013video.proto\022\013douyin.core\032\nuser.proto\"\256" +
      "\001\n\005Video\022\n\n\002id\030\001 \001(\003\022!\n\006author\030\002 \001(\0132\021.d" +
      "ouyin.core.User\022\020\n\010play_url\030\003 \001(\t\022\021\n\tcov" +
      "er_url\030\004 \001(\t\022\026\n\016favorite_count\030\005 \001(\003\022\025\n\r" +
      "comment_count\030\006 \001(\003\022\023\n\013is_favorite\030\007 \001(\010" +
      "\022\r\n\005title\030\010 \001(\t\"3\n\013FeedRequest\022\023\n\013latest" +
      "_time\030\001 \001(\003\022\017\n\007user_id\030\002 \001(\003\"r\n\014FeedResp" +
      "onse\022\023\n\013status_code\030\001 \001(\005\022\022\n\nstatus_msg\030" +
      "\002 \001(\t\022&\n\nvideo_list\030\003 \003(\0132\022.douyin.core." +
      "Video\022\021\n\tnext_time\030\004 \001(\003\"D\n\024PublishActio" +
      "nRequest\022\017\n\007user_id\030\001 \001(\003\022\014\n\004data\030\002 \001(\014\022" +
      "\r\n\005title\030\003 \001(\t\"@\n\025PublishActionResponse\022" +
      "\023\n\013status_code\030\001 \001(\005\022\022\n\nstatus_msg\030\002 \001(\t" +
      "\">\n\022PublishListRequest\022\024\n\014from_user_id\030\001" +
      " \001(\003\022\022\n\nto_user_id\030\002 \001(\003\"f\n\023PublishListR" +
      "esponse\022\023\n\013status_code\030\001 \001(\005\022\022\n\nstatus_m" +
      "sg\030\002 \001(\t\022&\n\nvideo_list\030\003 \003(\0132\022.douyin.co" +
      "re.Video\"&\n\023GetWorkCountRequest\022\017\n\007user_" +
      "id\030\001 \001(\003\"*\n\024GetWorkCountResponse\022\022\n\nwork" +
      "_count\030\001 \001(\0032\335\002\n\014VideoService\022E\n\014GetVide" +
      "oFeed\022\030.douyin.core.FeedRequest\032\031.douyin" +
      ".core.FeedResponse\"\000\022X\n\rPublishAction\022!." +
      "douyin.core.PublishActionRequest\032\".douyi" +
      "n.core.PublishActionResponse\"\000\022U\n\016GetPub" +
      "lishList\022\037.douyin.core.PublishListReques" +
      "t\032 .douyin.core.PublishListResponse\"\000\022U\n" +
      "\014GetWorkCount\022 .douyin.core.GetWorkCount" +
      "Request\032!.douyin.core.GetWorkCountRespon" +
      "se\"\000B.\n\027com.xty.dubbo_gen.videoB\021VideoSe" +
      "rviceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xty.dubbo_gen.user.UserServiceProto.getDescriptor(),
        });
    internal_static_douyin_core_Video_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_douyin_core_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_Video_descriptor,
        new java.lang.String[] { "Id", "Author", "PlayUrl", "CoverUrl", "FavoriteCount", "CommentCount", "IsFavorite", "Title", });
    internal_static_douyin_core_FeedRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_douyin_core_FeedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_FeedRequest_descriptor,
        new java.lang.String[] { "LatestTime", "UserId", });
    internal_static_douyin_core_FeedResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_douyin_core_FeedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_FeedResponse_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", "VideoList", "NextTime", });
    internal_static_douyin_core_PublishActionRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_douyin_core_PublishActionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_PublishActionRequest_descriptor,
        new java.lang.String[] { "UserId", "Data", "Title", });
    internal_static_douyin_core_PublishActionResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_douyin_core_PublishActionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_PublishActionResponse_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", });
    internal_static_douyin_core_PublishListRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_douyin_core_PublishListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_PublishListRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", });
    internal_static_douyin_core_PublishListResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_douyin_core_PublishListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_PublishListResponse_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", "VideoList", });
    internal_static_douyin_core_GetWorkCountRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_douyin_core_GetWorkCountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_GetWorkCountRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_douyin_core_GetWorkCountResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_douyin_core_GetWorkCountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_GetWorkCountResponse_descriptor,
        new java.lang.String[] { "WorkCount", });
    com.xty.dubbo_gen.user.UserServiceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
