// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video.proto

package com.xty.dubbo_gen.video;

/**
 * Protobuf type {@code douyin.core.Video}
 */
public final class Video extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:douyin.core.Video)
    VideoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Video.newBuilder() to construct.
  private Video(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Video() {
    playUrl_ = "";
    coverUrl_ = "";
    title_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Video();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_Video_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_Video_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xty.dubbo_gen.video.Video.class, com.xty.dubbo_gen.video.Video.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <pre>
   * 视频唯一标识
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int AUTHOR_FIELD_NUMBER = 2;
  private com.xty.dubbo_gen.user.User author_;
  /**
   * <pre>
   * 视频作者信息
   * </pre>
   *
   * <code>.douyin.core.User author = 2;</code>
   * @return Whether the author field is set.
   */
  @java.lang.Override
  public boolean hasAuthor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 视频作者信息
   * </pre>
   *
   * <code>.douyin.core.User author = 2;</code>
   * @return The author.
   */
  @java.lang.Override
  public com.xty.dubbo_gen.user.User getAuthor() {
    return author_ == null ? com.xty.dubbo_gen.user.User.getDefaultInstance() : author_;
  }
  /**
   * <pre>
   * 视频作者信息
   * </pre>
   *
   * <code>.douyin.core.User author = 2;</code>
   */
  @java.lang.Override
  public com.xty.dubbo_gen.user.UserOrBuilder getAuthorOrBuilder() {
    return author_ == null ? com.xty.dubbo_gen.user.User.getDefaultInstance() : author_;
  }

  public static final int PLAY_URL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object playUrl_ = "";
  /**
   * <pre>
   * 视频播放地址
   * </pre>
   *
   * <code>string play_url = 3;</code>
   * @return The playUrl.
   */
  @java.lang.Override
  public java.lang.String getPlayUrl() {
    java.lang.Object ref = playUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 视频播放地址
   * </pre>
   *
   * <code>string play_url = 3;</code>
   * @return The bytes for playUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayUrlBytes() {
    java.lang.Object ref = playUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COVER_URL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object coverUrl_ = "";
  /**
   * <pre>
   * 视频封面地址
   * </pre>
   *
   * <code>string cover_url = 4;</code>
   * @return The coverUrl.
   */
  @java.lang.Override
  public java.lang.String getCoverUrl() {
    java.lang.Object ref = coverUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      coverUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 视频封面地址
   * </pre>
   *
   * <code>string cover_url = 4;</code>
   * @return The bytes for coverUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCoverUrlBytes() {
    java.lang.Object ref = coverUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      coverUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAVORITE_COUNT_FIELD_NUMBER = 5;
  private long favoriteCount_ = 0L;
  /**
   * <pre>
   * 视频的点赞总数
   * </pre>
   *
   * <code>int64 favorite_count = 5;</code>
   * @return The favoriteCount.
   */
  @java.lang.Override
  public long getFavoriteCount() {
    return favoriteCount_;
  }

  public static final int COMMENT_COUNT_FIELD_NUMBER = 6;
  private long commentCount_ = 0L;
  /**
   * <pre>
   * 视频的评论总数
   * </pre>
   *
   * <code>int64 comment_count = 6;</code>
   * @return The commentCount.
   */
  @java.lang.Override
  public long getCommentCount() {
    return commentCount_;
  }

  public static final int IS_FAVORITE_FIELD_NUMBER = 7;
  private boolean isFavorite_ = false;
  /**
   * <pre>
   * true-已点赞，false-未点赞
   * </pre>
   *
   * <code>bool is_favorite = 7;</code>
   * @return The isFavorite.
   */
  @java.lang.Override
  public boolean getIsFavorite() {
    return isFavorite_;
  }

  public static final int TITLE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <pre>
   * 视频标题
   * </pre>
   *
   * <code>string title = 8;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 视频标题
   * </pre>
   *
   * <code>string title = 8;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getAuthor());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, playUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(coverUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, coverUrl_);
    }
    if (favoriteCount_ != 0L) {
      output.writeInt64(5, favoriteCount_);
    }
    if (commentCount_ != 0L) {
      output.writeInt64(6, commentCount_);
    }
    if (isFavorite_ != false) {
      output.writeBool(7, isFavorite_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, title_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAuthor());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, playUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(coverUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, coverUrl_);
    }
    if (favoriteCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, favoriteCount_);
    }
    if (commentCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, commentCount_);
    }
    if (isFavorite_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, isFavorite_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, title_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xty.dubbo_gen.video.Video)) {
      return super.equals(obj);
    }
    com.xty.dubbo_gen.video.Video other = (com.xty.dubbo_gen.video.Video) obj;

    if (getId()
        != other.getId()) return false;
    if (hasAuthor() != other.hasAuthor()) return false;
    if (hasAuthor()) {
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
    }
    if (!getPlayUrl()
        .equals(other.getPlayUrl())) return false;
    if (!getCoverUrl()
        .equals(other.getCoverUrl())) return false;
    if (getFavoriteCount()
        != other.getFavoriteCount()) return false;
    if (getCommentCount()
        != other.getCommentCount()) return false;
    if (getIsFavorite()
        != other.getIsFavorite()) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasAuthor()) {
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
    }
    hash = (37 * hash) + PLAY_URL_FIELD_NUMBER;
    hash = (53 * hash) + getPlayUrl().hashCode();
    hash = (37 * hash) + COVER_URL_FIELD_NUMBER;
    hash = (53 * hash) + getCoverUrl().hashCode();
    hash = (37 * hash) + FAVORITE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFavoriteCount());
    hash = (37 * hash) + COMMENT_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommentCount());
    hash = (37 * hash) + IS_FAVORITE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFavorite());
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xty.dubbo_gen.video.Video parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.video.Video parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.video.Video parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.video.Video parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.video.Video parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.video.Video parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.video.Video parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xty.dubbo_gen.video.Video parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xty.dubbo_gen.video.Video parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xty.dubbo_gen.video.Video parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xty.dubbo_gen.video.Video parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xty.dubbo_gen.video.Video parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xty.dubbo_gen.video.Video prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code douyin.core.Video}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:douyin.core.Video)
      com.xty.dubbo_gen.video.VideoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_Video_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_Video_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xty.dubbo_gen.video.Video.class, com.xty.dubbo_gen.video.Video.Builder.class);
    }

    // Construct using com.xty.dubbo_gen.video.Video.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAuthorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      author_ = null;
      if (authorBuilder_ != null) {
        authorBuilder_.dispose();
        authorBuilder_ = null;
      }
      playUrl_ = "";
      coverUrl_ = "";
      favoriteCount_ = 0L;
      commentCount_ = 0L;
      isFavorite_ = false;
      title_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xty.dubbo_gen.video.VideoServiceProto.internal_static_douyin_core_Video_descriptor;
    }

    @java.lang.Override
    public com.xty.dubbo_gen.video.Video getDefaultInstanceForType() {
      return com.xty.dubbo_gen.video.Video.getDefaultInstance();
    }

    @java.lang.Override
    public com.xty.dubbo_gen.video.Video build() {
      com.xty.dubbo_gen.video.Video result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xty.dubbo_gen.video.Video buildPartial() {
      com.xty.dubbo_gen.video.Video result = new com.xty.dubbo_gen.video.Video(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xty.dubbo_gen.video.Video result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.author_ = authorBuilder_ == null
            ? author_
            : authorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.playUrl_ = playUrl_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.coverUrl_ = coverUrl_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.favoriteCount_ = favoriteCount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.commentCount_ = commentCount_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.isFavorite_ = isFavorite_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.title_ = title_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xty.dubbo_gen.video.Video) {
        return mergeFrom((com.xty.dubbo_gen.video.Video)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xty.dubbo_gen.video.Video other) {
      if (other == com.xty.dubbo_gen.video.Video.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasAuthor()) {
        mergeAuthor(other.getAuthor());
      }
      if (!other.getPlayUrl().isEmpty()) {
        playUrl_ = other.playUrl_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getCoverUrl().isEmpty()) {
        coverUrl_ = other.coverUrl_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getFavoriteCount() != 0L) {
        setFavoriteCount(other.getFavoriteCount());
      }
      if (other.getCommentCount() != 0L) {
        setCommentCount(other.getCommentCount());
      }
      if (other.getIsFavorite() != false) {
        setIsFavorite(other.getIsFavorite());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getAuthorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              playUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              coverUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              favoriteCount_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              commentCount_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              isFavorite_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     * 视频唯一标识
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * 视频唯一标识
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频唯一标识
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private com.xty.dubbo_gen.user.User author_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xty.dubbo_gen.user.User, com.xty.dubbo_gen.user.User.Builder, com.xty.dubbo_gen.user.UserOrBuilder> authorBuilder_;
    /**
     * <pre>
     * 视频作者信息
     * </pre>
     *
     * <code>.douyin.core.User author = 2;</code>
     * @return Whether the author field is set.
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 视频作者信息
     * </pre>
     *
     * <code>.douyin.core.User author = 2;</code>
     * @return The author.
     */
    public com.xty.dubbo_gen.user.User getAuthor() {
      if (authorBuilder_ == null) {
        return author_ == null ? com.xty.dubbo_gen.user.User.getDefaultInstance() : author_;
      } else {
        return authorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 视频作者信息
     * </pre>
     *
     * <code>.douyin.core.User author = 2;</code>
     */
    public Builder setAuthor(com.xty.dubbo_gen.user.User value) {
      if (authorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        author_ = value;
      } else {
        authorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频作者信息
     * </pre>
     *
     * <code>.douyin.core.User author = 2;</code>
     */
    public Builder setAuthor(
        com.xty.dubbo_gen.user.User.Builder builderForValue) {
      if (authorBuilder_ == null) {
        author_ = builderForValue.build();
      } else {
        authorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频作者信息
     * </pre>
     *
     * <code>.douyin.core.User author = 2;</code>
     */
    public Builder mergeAuthor(com.xty.dubbo_gen.user.User value) {
      if (authorBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          author_ != null &&
          author_ != com.xty.dubbo_gen.user.User.getDefaultInstance()) {
          getAuthorBuilder().mergeFrom(value);
        } else {
          author_ = value;
        }
      } else {
        authorBuilder_.mergeFrom(value);
      }
      if (author_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 视频作者信息
     * </pre>
     *
     * <code>.douyin.core.User author = 2;</code>
     */
    public Builder clearAuthor() {
      bitField0_ = (bitField0_ & ~0x00000002);
      author_ = null;
      if (authorBuilder_ != null) {
        authorBuilder_.dispose();
        authorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频作者信息
     * </pre>
     *
     * <code>.douyin.core.User author = 2;</code>
     */
    public com.xty.dubbo_gen.user.User.Builder getAuthorBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getAuthorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 视频作者信息
     * </pre>
     *
     * <code>.douyin.core.User author = 2;</code>
     */
    public com.xty.dubbo_gen.user.UserOrBuilder getAuthorOrBuilder() {
      if (authorBuilder_ != null) {
        return authorBuilder_.getMessageOrBuilder();
      } else {
        return author_ == null ?
            com.xty.dubbo_gen.user.User.getDefaultInstance() : author_;
      }
    }
    /**
     * <pre>
     * 视频作者信息
     * </pre>
     *
     * <code>.douyin.core.User author = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xty.dubbo_gen.user.User, com.xty.dubbo_gen.user.User.Builder, com.xty.dubbo_gen.user.UserOrBuilder> 
        getAuthorFieldBuilder() {
      if (authorBuilder_ == null) {
        authorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xty.dubbo_gen.user.User, com.xty.dubbo_gen.user.User.Builder, com.xty.dubbo_gen.user.UserOrBuilder>(
                getAuthor(),
                getParentForChildren(),
                isClean());
        author_ = null;
      }
      return authorBuilder_;
    }

    private java.lang.Object playUrl_ = "";
    /**
     * <pre>
     * 视频播放地址
     * </pre>
     *
     * <code>string play_url = 3;</code>
     * @return The playUrl.
     */
    public java.lang.String getPlayUrl() {
      java.lang.Object ref = playUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 视频播放地址
     * </pre>
     *
     * <code>string play_url = 3;</code>
     * @return The bytes for playUrl.
     */
    public com.google.protobuf.ByteString
        getPlayUrlBytes() {
      java.lang.Object ref = playUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 视频播放地址
     * </pre>
     *
     * <code>string play_url = 3;</code>
     * @param value The playUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPlayUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      playUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频播放地址
     * </pre>
     *
     * <code>string play_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayUrl() {
      playUrl_ = getDefaultInstance().getPlayUrl();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频播放地址
     * </pre>
     *
     * <code>string play_url = 3;</code>
     * @param value The bytes for playUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPlayUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      playUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object coverUrl_ = "";
    /**
     * <pre>
     * 视频封面地址
     * </pre>
     *
     * <code>string cover_url = 4;</code>
     * @return The coverUrl.
     */
    public java.lang.String getCoverUrl() {
      java.lang.Object ref = coverUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coverUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 视频封面地址
     * </pre>
     *
     * <code>string cover_url = 4;</code>
     * @return The bytes for coverUrl.
     */
    public com.google.protobuf.ByteString
        getCoverUrlBytes() {
      java.lang.Object ref = coverUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coverUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 视频封面地址
     * </pre>
     *
     * <code>string cover_url = 4;</code>
     * @param value The coverUrl to set.
     * @return This builder for chaining.
     */
    public Builder setCoverUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      coverUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频封面地址
     * </pre>
     *
     * <code>string cover_url = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoverUrl() {
      coverUrl_ = getDefaultInstance().getCoverUrl();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频封面地址
     * </pre>
     *
     * <code>string cover_url = 4;</code>
     * @param value The bytes for coverUrl to set.
     * @return This builder for chaining.
     */
    public Builder setCoverUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      coverUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long favoriteCount_ ;
    /**
     * <pre>
     * 视频的点赞总数
     * </pre>
     *
     * <code>int64 favorite_count = 5;</code>
     * @return The favoriteCount.
     */
    @java.lang.Override
    public long getFavoriteCount() {
      return favoriteCount_;
    }
    /**
     * <pre>
     * 视频的点赞总数
     * </pre>
     *
     * <code>int64 favorite_count = 5;</code>
     * @param value The favoriteCount to set.
     * @return This builder for chaining.
     */
    public Builder setFavoriteCount(long value) {

      favoriteCount_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频的点赞总数
     * </pre>
     *
     * <code>int64 favorite_count = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFavoriteCount() {
      bitField0_ = (bitField0_ & ~0x00000010);
      favoriteCount_ = 0L;
      onChanged();
      return this;
    }

    private long commentCount_ ;
    /**
     * <pre>
     * 视频的评论总数
     * </pre>
     *
     * <code>int64 comment_count = 6;</code>
     * @return The commentCount.
     */
    @java.lang.Override
    public long getCommentCount() {
      return commentCount_;
    }
    /**
     * <pre>
     * 视频的评论总数
     * </pre>
     *
     * <code>int64 comment_count = 6;</code>
     * @param value The commentCount to set.
     * @return This builder for chaining.
     */
    public Builder setCommentCount(long value) {

      commentCount_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频的评论总数
     * </pre>
     *
     * <code>int64 comment_count = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommentCount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      commentCount_ = 0L;
      onChanged();
      return this;
    }

    private boolean isFavorite_ ;
    /**
     * <pre>
     * true-已点赞，false-未点赞
     * </pre>
     *
     * <code>bool is_favorite = 7;</code>
     * @return The isFavorite.
     */
    @java.lang.Override
    public boolean getIsFavorite() {
      return isFavorite_;
    }
    /**
     * <pre>
     * true-已点赞，false-未点赞
     * </pre>
     *
     * <code>bool is_favorite = 7;</code>
     * @param value The isFavorite to set.
     * @return This builder for chaining.
     */
    public Builder setIsFavorite(boolean value) {

      isFavorite_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * true-已点赞，false-未点赞
     * </pre>
     *
     * <code>bool is_favorite = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsFavorite() {
      bitField0_ = (bitField0_ & ~0x00000040);
      isFavorite_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <pre>
     * 视频标题
     * </pre>
     *
     * <code>string title = 8;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 视频标题
     * </pre>
     *
     * <code>string title = 8;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 视频标题
     * </pre>
     *
     * <code>string title = 8;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频标题
     * </pre>
     *
     * <code>string title = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频标题
     * </pre>
     *
     * <code>string title = 8;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:douyin.core.Video)
  }

  // @@protoc_insertion_point(class_scope:douyin.core.Video)
  private static final com.xty.dubbo_gen.video.Video DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xty.dubbo_gen.video.Video();
  }

  public static com.xty.dubbo_gen.video.Video getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Video>
      PARSER = new com.google.protobuf.AbstractParser<Video>() {
    @java.lang.Override
    public Video parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Video> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Video> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xty.dubbo_gen.video.Video getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

