// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.xty.dubbo_gen.user;

public interface UserInfoByNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.core.UserInfoByNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
