// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.xty.dubbo_gen.user;

public final class UserServiceProto {
  private UserServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserRegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserRegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserRegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserRegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserLoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserLoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserLoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserLoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserInfoByNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserInfoByNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserInfoByNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserInfoByNameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserExitsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserExitsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_core_UserExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_core_UserExistsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\013douyin.core\"\343\001\n\004User\022\n\n\002id" +
      "\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\024\n\014follow_count\030\003 \001" +
      "(\003\022\026\n\016follower_count\030\004 \001(\003\022\021\n\tis_follow\030" +
      "\005 \001(\010\022\016\n\006avatar\030\006 \001(\t\022\030\n\020background_imag" +
      "e\030\007 \001(\t\022\021\n\tsignature\030\010 \001(\t\022\027\n\017total_favo" +
      "rited\030\t \001(\003\022\022\n\nwork_count\030\n \001(\003\022\026\n\016favor" +
      "ite_count\030\013 \001(\003\"9\n\023UserRegisterRequest\022\020" +
      "\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"_\n\024Us" +
      "erRegisterResponse\022\023\n\013status_code\030\001 \001(\005\022" +
      "\022\n\nstatus_msg\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\003\022\r\n\005" +
      "token\030\004 \001(\t\"6\n\020UserLoginRequest\022\020\n\010usern" +
      "ame\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\\\n\021UserLogin" +
      "Response\022\023\n\013status_code\030\001 \001(\005\022\022\n\nstatus_" +
      "msg\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\003\022\r\n\005token\030\004 \001(" +
      "\t\";\n\017UserInfoRequest\022\024\n\014from_user_id\030\001 \001" +
      "(\003\022\022\n\nto_user_id\030\002 \001(\003\"\\\n\020UserInfoRespon" +
      "se\022\023\n\013status_code\030\001 \001(\005\022\022\n\nstatus_msg\030\002 " +
      "\001(\t\022\037\n\004user\030\003 \001(\0132\021.douyin.core.User\")\n\025" +
      "UserInfoByNameRequest\022\020\n\010username\030\001 \001(\t\"" +
      "d\n\026UserInfoByNameResponse\022\023\n\013status_code" +
      "\030\001 \001(\005\022\022\n\nstatus_msg\030\002 \001(\t\022\017\n\007user_id\030\003 " +
      "\001(\003\022\020\n\010password\030\004 \001(\t\"$\n\020UserExitsReques" +
      "t\022\020\n\010username\030\001 \001(\t\"#\n\022UserExistsRespons" +
      "e\022\r\n\005exist\030\001 \001(\0102\370\001\n\013UserService\022Q\n\010Regi" +
      "ster\022 .douyin.core.UserRegisterRequest\032!" +
      ".douyin.core.UserRegisterResponse\"\000\022H\n\005L" +
      "ogin\022\035.douyin.core.UserLoginRequest\032\036.do" +
      "uyin.core.UserLoginResponse\"\000\022L\n\013GetUser" +
      "Info\022\034.douyin.core.UserInfoRequest\032\035.dou" +
      "yin.core.UserInfoResponse\"\000B,\n\026com.xty.d" +
      "ubbo_gen.userB\020UserServiceProtoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_douyin_core_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_douyin_core_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_User_descriptor,
        new java.lang.String[] { "Id", "Name", "FollowCount", "FollowerCount", "IsFollow", "Avatar", "BackgroundImage", "Signature", "TotalFavorited", "WorkCount", "FavoriteCount", });
    internal_static_douyin_core_UserRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_douyin_core_UserRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserRegisterRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_douyin_core_UserRegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_douyin_core_UserRegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserRegisterResponse_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", "UserId", "Token", });
    internal_static_douyin_core_UserLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_douyin_core_UserLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserLoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_douyin_core_UserLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_douyin_core_UserLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserLoginResponse_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", "UserId", "Token", });
    internal_static_douyin_core_UserInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_douyin_core_UserInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserInfoRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", });
    internal_static_douyin_core_UserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_douyin_core_UserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserInfoResponse_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", "User", });
    internal_static_douyin_core_UserInfoByNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_douyin_core_UserInfoByNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserInfoByNameRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_douyin_core_UserInfoByNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_douyin_core_UserInfoByNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserInfoByNameResponse_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", "UserId", "Password", });
    internal_static_douyin_core_UserExitsRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_douyin_core_UserExitsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserExitsRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_douyin_core_UserExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_douyin_core_UserExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_core_UserExistsResponse_descriptor,
        new java.lang.String[] { "Exist", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
