// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.xty.dubbo_gen.user;

/**
 * Protobuf type {@code douyin.core.User}
 */
public final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:douyin.core.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    name_ = "";
    avatar_ = "";
    backgroundImage_ = "";
    signature_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new User();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xty.dubbo_gen.user.UserServiceProto.internal_static_douyin_core_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xty.dubbo_gen.user.UserServiceProto.internal_static_douyin_core_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xty.dubbo_gen.user.User.class, com.xty.dubbo_gen.user.User.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <pre>
   * 用户id
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * 用户名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户名称
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOLLOW_COUNT_FIELD_NUMBER = 3;
  private long followCount_ = 0L;
  /**
   * <pre>
   * 关注总数
   * </pre>
   *
   * <code>int64 follow_count = 3;</code>
   * @return The followCount.
   */
  @java.lang.Override
  public long getFollowCount() {
    return followCount_;
  }

  public static final int FOLLOWER_COUNT_FIELD_NUMBER = 4;
  private long followerCount_ = 0L;
  /**
   * <pre>
   * 粉丝总数
   * </pre>
   *
   * <code>int64 follower_count = 4;</code>
   * @return The followerCount.
   */
  @java.lang.Override
  public long getFollowerCount() {
    return followerCount_;
  }

  public static final int IS_FOLLOW_FIELD_NUMBER = 5;
  private boolean isFollow_ = false;
  /**
   * <pre>
   * true-已关注，false-未关注
   * </pre>
   *
   * <code>bool is_follow = 5;</code>
   * @return The isFollow.
   */
  @java.lang.Override
  public boolean getIsFollow() {
    return isFollow_;
  }

  public static final int AVATAR_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object avatar_ = "";
  /**
   * <pre>
   *用户头像
   * </pre>
   *
   * <code>string avatar = 6;</code>
   * @return The avatar.
   */
  @java.lang.Override
  public java.lang.String getAvatar() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatar_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *用户头像
   * </pre>
   *
   * <code>string avatar = 6;</code>
   * @return The bytes for avatar.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAvatarBytes() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BACKGROUND_IMAGE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object backgroundImage_ = "";
  /**
   * <pre>
   *用户个人页顶部大图
   * </pre>
   *
   * <code>string background_image = 7;</code>
   * @return The backgroundImage.
   */
  @java.lang.Override
  public java.lang.String getBackgroundImage() {
    java.lang.Object ref = backgroundImage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      backgroundImage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *用户个人页顶部大图
   * </pre>
   *
   * <code>string background_image = 7;</code>
   * @return The bytes for backgroundImage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBackgroundImageBytes() {
    java.lang.Object ref = backgroundImage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      backgroundImage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNATURE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object signature_ = "";
  /**
   * <pre>
   *个人简介
   * </pre>
   *
   * <code>string signature = 8;</code>
   * @return The signature.
   */
  @java.lang.Override
  public java.lang.String getSignature() {
    java.lang.Object ref = signature_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      signature_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *个人简介
   * </pre>
   *
   * <code>string signature = 8;</code>
   * @return The bytes for signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSignatureBytes() {
    java.lang.Object ref = signature_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_FAVORITED_FIELD_NUMBER = 9;
  private long totalFavorited_ = 0L;
  /**
   * <pre>
   *获赞数量
   * </pre>
   *
   * <code>int64 total_favorited = 9;</code>
   * @return The totalFavorited.
   */
  @java.lang.Override
  public long getTotalFavorited() {
    return totalFavorited_;
  }

  public static final int WORK_COUNT_FIELD_NUMBER = 10;
  private long workCount_ = 0L;
  /**
   * <pre>
   *作品数量
   * </pre>
   *
   * <code>int64 work_count = 10;</code>
   * @return The workCount.
   */
  @java.lang.Override
  public long getWorkCount() {
    return workCount_;
  }

  public static final int FAVORITE_COUNT_FIELD_NUMBER = 11;
  private long favoriteCount_ = 0L;
  /**
   * <pre>
   *点赞数量
   * </pre>
   *
   * <code>int64 favorite_count = 11;</code>
   * @return The favoriteCount.
   */
  @java.lang.Override
  public long getFavoriteCount() {
    return favoriteCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (followCount_ != 0L) {
      output.writeInt64(3, followCount_);
    }
    if (followerCount_ != 0L) {
      output.writeInt64(4, followerCount_);
    }
    if (isFollow_ != false) {
      output.writeBool(5, isFollow_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatar_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, avatar_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(backgroundImage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, backgroundImage_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signature_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, signature_);
    }
    if (totalFavorited_ != 0L) {
      output.writeInt64(9, totalFavorited_);
    }
    if (workCount_ != 0L) {
      output.writeInt64(10, workCount_);
    }
    if (favoriteCount_ != 0L) {
      output.writeInt64(11, favoriteCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (followCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, followCount_);
    }
    if (followerCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, followerCount_);
    }
    if (isFollow_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isFollow_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatar_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, avatar_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(backgroundImage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, backgroundImage_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signature_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, signature_);
    }
    if (totalFavorited_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, totalFavorited_);
    }
    if (workCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, workCount_);
    }
    if (favoriteCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, favoriteCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xty.dubbo_gen.user.User)) {
      return super.equals(obj);
    }
    com.xty.dubbo_gen.user.User other = (com.xty.dubbo_gen.user.User) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getFollowCount()
        != other.getFollowCount()) return false;
    if (getFollowerCount()
        != other.getFollowerCount()) return false;
    if (getIsFollow()
        != other.getIsFollow()) return false;
    if (!getAvatar()
        .equals(other.getAvatar())) return false;
    if (!getBackgroundImage()
        .equals(other.getBackgroundImage())) return false;
    if (!getSignature()
        .equals(other.getSignature())) return false;
    if (getTotalFavorited()
        != other.getTotalFavorited()) return false;
    if (getWorkCount()
        != other.getWorkCount()) return false;
    if (getFavoriteCount()
        != other.getFavoriteCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + FOLLOW_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFollowCount());
    hash = (37 * hash) + FOLLOWER_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFollowerCount());
    hash = (37 * hash) + IS_FOLLOW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFollow());
    hash = (37 * hash) + AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getAvatar().hashCode();
    hash = (37 * hash) + BACKGROUND_IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getBackgroundImage().hashCode();
    hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getSignature().hashCode();
    hash = (37 * hash) + TOTAL_FAVORITED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalFavorited());
    hash = (37 * hash) + WORK_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWorkCount());
    hash = (37 * hash) + FAVORITE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFavoriteCount());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xty.dubbo_gen.user.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.user.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.user.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.user.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.user.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.user.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.user.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xty.dubbo_gen.user.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xty.dubbo_gen.user.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xty.dubbo_gen.user.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xty.dubbo_gen.user.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xty.dubbo_gen.user.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xty.dubbo_gen.user.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code douyin.core.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:douyin.core.User)
      com.xty.dubbo_gen.user.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xty.dubbo_gen.user.UserServiceProto.internal_static_douyin_core_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xty.dubbo_gen.user.UserServiceProto.internal_static_douyin_core_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xty.dubbo_gen.user.User.class, com.xty.dubbo_gen.user.User.Builder.class);
    }

    // Construct using com.xty.dubbo_gen.user.User.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      name_ = "";
      followCount_ = 0L;
      followerCount_ = 0L;
      isFollow_ = false;
      avatar_ = "";
      backgroundImage_ = "";
      signature_ = "";
      totalFavorited_ = 0L;
      workCount_ = 0L;
      favoriteCount_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xty.dubbo_gen.user.UserServiceProto.internal_static_douyin_core_User_descriptor;
    }

    @java.lang.Override
    public com.xty.dubbo_gen.user.User getDefaultInstanceForType() {
      return com.xty.dubbo_gen.user.User.getDefaultInstance();
    }

    @java.lang.Override
    public com.xty.dubbo_gen.user.User build() {
      com.xty.dubbo_gen.user.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xty.dubbo_gen.user.User buildPartial() {
      com.xty.dubbo_gen.user.User result = new com.xty.dubbo_gen.user.User(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xty.dubbo_gen.user.User result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.followCount_ = followCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.followerCount_ = followerCount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isFollow_ = isFollow_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.avatar_ = avatar_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.backgroundImage_ = backgroundImage_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.signature_ = signature_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.totalFavorited_ = totalFavorited_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.workCount_ = workCount_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.favoriteCount_ = favoriteCount_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xty.dubbo_gen.user.User) {
        return mergeFrom((com.xty.dubbo_gen.user.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xty.dubbo_gen.user.User other) {
      if (other == com.xty.dubbo_gen.user.User.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getFollowCount() != 0L) {
        setFollowCount(other.getFollowCount());
      }
      if (other.getFollowerCount() != 0L) {
        setFollowerCount(other.getFollowerCount());
      }
      if (other.getIsFollow() != false) {
        setIsFollow(other.getIsFollow());
      }
      if (!other.getAvatar().isEmpty()) {
        avatar_ = other.avatar_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getBackgroundImage().isEmpty()) {
        backgroundImage_ = other.backgroundImage_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getSignature().isEmpty()) {
        signature_ = other.signature_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getTotalFavorited() != 0L) {
        setTotalFavorited(other.getTotalFavorited());
      }
      if (other.getWorkCount() != 0L) {
        setWorkCount(other.getWorkCount());
      }
      if (other.getFavoriteCount() != 0L) {
        setFavoriteCount(other.getFavoriteCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              followCount_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              followerCount_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              isFollow_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              avatar_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              backgroundImage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              signature_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              totalFavorited_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              workCount_ = input.readInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              favoriteCount_ = input.readInt64();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long followCount_ ;
    /**
     * <pre>
     * 关注总数
     * </pre>
     *
     * <code>int64 follow_count = 3;</code>
     * @return The followCount.
     */
    @java.lang.Override
    public long getFollowCount() {
      return followCount_;
    }
    /**
     * <pre>
     * 关注总数
     * </pre>
     *
     * <code>int64 follow_count = 3;</code>
     * @param value The followCount to set.
     * @return This builder for chaining.
     */
    public Builder setFollowCount(long value) {

      followCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关注总数
     * </pre>
     *
     * <code>int64 follow_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFollowCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      followCount_ = 0L;
      onChanged();
      return this;
    }

    private long followerCount_ ;
    /**
     * <pre>
     * 粉丝总数
     * </pre>
     *
     * <code>int64 follower_count = 4;</code>
     * @return The followerCount.
     */
    @java.lang.Override
    public long getFollowerCount() {
      return followerCount_;
    }
    /**
     * <pre>
     * 粉丝总数
     * </pre>
     *
     * <code>int64 follower_count = 4;</code>
     * @param value The followerCount to set.
     * @return This builder for chaining.
     */
    public Builder setFollowerCount(long value) {

      followerCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 粉丝总数
     * </pre>
     *
     * <code>int64 follower_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFollowerCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      followerCount_ = 0L;
      onChanged();
      return this;
    }

    private boolean isFollow_ ;
    /**
     * <pre>
     * true-已关注，false-未关注
     * </pre>
     *
     * <code>bool is_follow = 5;</code>
     * @return The isFollow.
     */
    @java.lang.Override
    public boolean getIsFollow() {
      return isFollow_;
    }
    /**
     * <pre>
     * true-已关注，false-未关注
     * </pre>
     *
     * <code>bool is_follow = 5;</code>
     * @param value The isFollow to set.
     * @return This builder for chaining.
     */
    public Builder setIsFollow(boolean value) {

      isFollow_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * true-已关注，false-未关注
     * </pre>
     *
     * <code>bool is_follow = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsFollow() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isFollow_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object avatar_ = "";
    /**
     * <pre>
     *用户头像
     * </pre>
     *
     * <code>string avatar = 6;</code>
     * @return The avatar.
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *用户头像
     * </pre>
     *
     * <code>string avatar = 6;</code>
     * @return The bytes for avatar.
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *用户头像
     * </pre>
     *
     * <code>string avatar = 6;</code>
     * @param value The avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatar(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      avatar_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户头像
     * </pre>
     *
     * <code>string avatar = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvatar() {
      avatar_ = getDefaultInstance().getAvatar();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户头像
     * </pre>
     *
     * <code>string avatar = 6;</code>
     * @param value The bytes for avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      avatar_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object backgroundImage_ = "";
    /**
     * <pre>
     *用户个人页顶部大图
     * </pre>
     *
     * <code>string background_image = 7;</code>
     * @return The backgroundImage.
     */
    public java.lang.String getBackgroundImage() {
      java.lang.Object ref = backgroundImage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backgroundImage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *用户个人页顶部大图
     * </pre>
     *
     * <code>string background_image = 7;</code>
     * @return The bytes for backgroundImage.
     */
    public com.google.protobuf.ByteString
        getBackgroundImageBytes() {
      java.lang.Object ref = backgroundImage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backgroundImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *用户个人页顶部大图
     * </pre>
     *
     * <code>string background_image = 7;</code>
     * @param value The backgroundImage to set.
     * @return This builder for chaining.
     */
    public Builder setBackgroundImage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      backgroundImage_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户个人页顶部大图
     * </pre>
     *
     * <code>string background_image = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearBackgroundImage() {
      backgroundImage_ = getDefaultInstance().getBackgroundImage();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户个人页顶部大图
     * </pre>
     *
     * <code>string background_image = 7;</code>
     * @param value The bytes for backgroundImage to set.
     * @return This builder for chaining.
     */
    public Builder setBackgroundImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      backgroundImage_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object signature_ = "";
    /**
     * <pre>
     *个人简介
     * </pre>
     *
     * <code>string signature = 8;</code>
     * @return The signature.
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *个人简介
     * </pre>
     *
     * <code>string signature = 8;</code>
     * @return The bytes for signature.
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *个人简介
     * </pre>
     *
     * <code>string signature = 8;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      signature_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *个人简介
     * </pre>
     *
     * <code>string signature = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      signature_ = getDefaultInstance().getSignature();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *个人简介
     * </pre>
     *
     * <code>string signature = 8;</code>
     * @param value The bytes for signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      signature_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private long totalFavorited_ ;
    /**
     * <pre>
     *获赞数量
     * </pre>
     *
     * <code>int64 total_favorited = 9;</code>
     * @return The totalFavorited.
     */
    @java.lang.Override
    public long getTotalFavorited() {
      return totalFavorited_;
    }
    /**
     * <pre>
     *获赞数量
     * </pre>
     *
     * <code>int64 total_favorited = 9;</code>
     * @param value The totalFavorited to set.
     * @return This builder for chaining.
     */
    public Builder setTotalFavorited(long value) {

      totalFavorited_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *获赞数量
     * </pre>
     *
     * <code>int64 total_favorited = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalFavorited() {
      bitField0_ = (bitField0_ & ~0x00000100);
      totalFavorited_ = 0L;
      onChanged();
      return this;
    }

    private long workCount_ ;
    /**
     * <pre>
     *作品数量
     * </pre>
     *
     * <code>int64 work_count = 10;</code>
     * @return The workCount.
     */
    @java.lang.Override
    public long getWorkCount() {
      return workCount_;
    }
    /**
     * <pre>
     *作品数量
     * </pre>
     *
     * <code>int64 work_count = 10;</code>
     * @param value The workCount to set.
     * @return This builder for chaining.
     */
    public Builder setWorkCount(long value) {

      workCount_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *作品数量
     * </pre>
     *
     * <code>int64 work_count = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkCount() {
      bitField0_ = (bitField0_ & ~0x00000200);
      workCount_ = 0L;
      onChanged();
      return this;
    }

    private long favoriteCount_ ;
    /**
     * <pre>
     *点赞数量
     * </pre>
     *
     * <code>int64 favorite_count = 11;</code>
     * @return The favoriteCount.
     */
    @java.lang.Override
    public long getFavoriteCount() {
      return favoriteCount_;
    }
    /**
     * <pre>
     *点赞数量
     * </pre>
     *
     * <code>int64 favorite_count = 11;</code>
     * @param value The favoriteCount to set.
     * @return This builder for chaining.
     */
    public Builder setFavoriteCount(long value) {

      favoriteCount_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *点赞数量
     * </pre>
     *
     * <code>int64 favorite_count = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearFavoriteCount() {
      bitField0_ = (bitField0_ & ~0x00000400);
      favoriteCount_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:douyin.core.User)
  }

  // @@protoc_insertion_point(class_scope:douyin.core.User)
  private static final com.xty.dubbo_gen.user.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xty.dubbo_gen.user.User();
  }

  public static com.xty.dubbo_gen.user.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xty.dubbo_gen.user.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

