// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.xty.dubbo_gen.user;

public interface UserRegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.core.UserRegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 状态码，0-成功，其他值-失败
   * </pre>
   *
   * <code>int32 status_code = 1;</code>
   * @return The statusCode.
   */
  int getStatusCode();

  /**
   * <pre>
   * 返回状态描述
   * </pre>
   *
   * <code>string status_msg = 2;</code>
   * @return The statusMsg.
   */
  java.lang.String getStatusMsg();
  /**
   * <pre>
   * 返回状态描述
   * </pre>
   *
   * <code>string status_msg = 2;</code>
   * @return The bytes for statusMsg.
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();

  /**
   * <pre>
   * 用户id
   * </pre>
   *
   * <code>int64 user_id = 3;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <pre>
   * 用户鉴权token
   * </pre>
   *
   * <code>string token = 4;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   * 用户鉴权token
   * </pre>
   *
   * <code>string token = 4;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
