// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.xty.dubbo_gen.user;

public interface UserInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.core.UserInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 调用者id
   * </pre>
   *
   * <code>int64 from_user_id = 1;</code>
   * @return The fromUserId.
   */
  long getFromUserId();

  /**
   * <pre>
   * 被调用方id
   * </pre>
   *
   * <code>int64 to_user_id = 2;</code>
   * @return The toUserId.
   */
  long getToUserId();
}
