// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.xty.dubbo_gen.user;

public interface UserExistsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.core.UserExistsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool exist = 1;</code>
   * @return The exist.
   */
  boolean getExist();
}
