// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite.proto

package com.xty.dubbo_gen.favorite;

public final class FavoriteServiceProto {
  private FavoriteServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_FavoriteActionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_FavoriteActionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_FavoriteActionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_FavoriteActionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_FavoriteListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_FavoriteListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_FavoriteListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_FavoriteListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_IsUserFavoriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_IsUserFavoriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_IsUserFavoriteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_IsUserFavoriteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_GetVideoFavoriteCountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_GetVideoFavoriteCountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_GetUserTotalFavoriteCountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_GetUserTotalFavoriteCountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_GetUserFavoriteCountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_GetUserFavoriteCountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_douyin_extra_first_GetFavoriteCountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_douyin_extra_first_GetFavoriteCountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016favorite.proto\022\022douyin.extra.first\"\265\001\n" +
      "\005Video\022\n\n\002id\030\001 \001(\003\022(\n\006author\030\002 \001(\0132\030.dou" +
      "yin.extra.first.User\022\020\n\010play_url\030\003 \001(\t\022\021" +
      "\n\tcover_url\030\004 \001(\t\022\026\n\016favorite_count\030\005 \001(" +
      "\003\022\025\n\rcomment_count\030\006 \001(\003\022\023\n\013is_favorite\030" +
      "\007 \001(\010\022\r\n\005title\030\010 \001(\t\"\343\001\n\004User\022\n\n\002id\030\001 \001(" +
      "\003\022\014\n\004name\030\002 \001(\t\022\024\n\014follow_count\030\003 \001(\003\022\026\n" +
      "\016follower_count\030\004 \001(\003\022\021\n\tis_follow\030\005 \001(\010" +
      "\022\016\n\006avatar\030\006 \001(\t\022\030\n\020background_image\030\007 \001" +
      "(\t\022\021\n\tsignature\030\010 \001(\t\022\027\n\017total_favorited" +
      "\030\t \001(\003\022\022\n\nwork_count\030\n \001(\003\022\026\n\016favorite_c" +
      "ount\030\013 \001(\003\"O\n\025FavoriteActionRequest\022\017\n\007u" +
      "ser_id\030\001 \001(\003\022\020\n\010video_id\030\002 \001(\003\022\023\n\013action" +
      "_type\030\003 \001(\005\"A\n\026FavoriteActionResponse\022\023\n" +
      "\013status_code\030\001 \001(\005\022\022\n\nstatus_msg\030\002 \001(\t\"?" +
      "\n\023FavoriteListRequest\022\024\n\014from_user_id\030\001 " +
      "\001(\003\022\022\n\nto_user_id\030\002 \001(\003\"n\n\024FavoriteListR" +
      "esponse\022\023\n\013status_code\030\001 \001(\005\022\022\n\nstatus_m" +
      "sg\030\002 \001(\t\022-\n\nvideo_list\030\003 \003(\0132\031.douyin.ex" +
      "tra.first.Video\":\n\025IsUserFavoriteRequest" +
      "\022\017\n\007user_id\030\001 \001(\003\022\020\n\010video_id\030\002 \001(\003\"-\n\026I" +
      "sUserFavoriteResponse\022\023\n\013is_favorite\030\001 \001" +
      "(\010\"0\n\034GetVideoFavoriteCountRequest\022\020\n\010vi" +
      "deo_id\030\001 \001(\003\"3\n GetUserTotalFavoriteCoun" +
      "tRequest\022\017\n\007user_id\030\001 \001(\003\".\n\033GetUserFavo" +
      "riteCountRequest\022\017\n\007user_id\030\001 \001(\003\"2\n\030Get" +
      "FavoriteCountResponse\022\026\n\016favorite_count\030" +
      "\001 \001(\0032\307\005\n\017FavoriteService\022i\n\016FavoriteAct" +
      "ion\022).douyin.extra.first.FavoriteActionR" +
      "equest\032*.douyin.extra.first.FavoriteActi" +
      "onResponse\"\000\022f\n\017GetFavoriteList\022\'.douyin" +
      ".extra.first.FavoriteListRequest\032(.douyi" +
      "n.extra.first.FavoriteListResponse\"\000\022y\n\025" +
      "GetVideoFavoriteCount\0220.douyin.extra.fir" +
      "st.GetVideoFavoriteCountRequest\032,.douyin" +
      ".extra.first.GetFavoriteCountResponse\"\000\022" +
      "w\n\024GetUserFavoriteCount\022/.douyin.extra.f" +
      "irst.GetUserFavoriteCountRequest\032,.douyi" +
      "n.extra.first.GetFavoriteCountResponse\"\000" +
      "\022\201\001\n\031GetUserTotalFavoriteCount\0224.douyin." +
      "extra.first.GetUserTotalFavoriteCountReq" +
      "uest\032,.douyin.extra.first.GetFavoriteCou" +
      "ntResponse\"\000\022i\n\016IsUserFavorite\022).douyin." +
      "extra.first.IsUserFavoriteRequest\032*.douy" +
      "in.extra.first.IsUserFavoriteResponse\"\000B" +
      "4\n\032com.xty.dubbo_gen.favoriteB\024FavoriteS" +
      "erviceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_douyin_extra_first_Video_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_douyin_extra_first_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_Video_descriptor,
        new java.lang.String[] { "Id", "Author", "PlayUrl", "CoverUrl", "FavoriteCount", "CommentCount", "IsFavorite", "Title", });
    internal_static_douyin_extra_first_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_douyin_extra_first_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_User_descriptor,
        new java.lang.String[] { "Id", "Name", "FollowCount", "FollowerCount", "IsFollow", "Avatar", "BackgroundImage", "Signature", "TotalFavorited", "WorkCount", "FavoriteCount", });
    internal_static_douyin_extra_first_FavoriteActionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_douyin_extra_first_FavoriteActionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_FavoriteActionRequest_descriptor,
        new java.lang.String[] { "UserId", "VideoId", "ActionType", });
    internal_static_douyin_extra_first_FavoriteActionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_douyin_extra_first_FavoriteActionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_FavoriteActionResponse_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", });
    internal_static_douyin_extra_first_FavoriteListRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_douyin_extra_first_FavoriteListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_FavoriteListRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", });
    internal_static_douyin_extra_first_FavoriteListResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_douyin_extra_first_FavoriteListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_FavoriteListResponse_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMsg", "VideoList", });
    internal_static_douyin_extra_first_IsUserFavoriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_douyin_extra_first_IsUserFavoriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_IsUserFavoriteRequest_descriptor,
        new java.lang.String[] { "UserId", "VideoId", });
    internal_static_douyin_extra_first_IsUserFavoriteResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_douyin_extra_first_IsUserFavoriteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_IsUserFavoriteResponse_descriptor,
        new java.lang.String[] { "IsFavorite", });
    internal_static_douyin_extra_first_GetVideoFavoriteCountRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_douyin_extra_first_GetVideoFavoriteCountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_GetVideoFavoriteCountRequest_descriptor,
        new java.lang.String[] { "VideoId", });
    internal_static_douyin_extra_first_GetUserTotalFavoriteCountRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_douyin_extra_first_GetUserTotalFavoriteCountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_GetUserTotalFavoriteCountRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_douyin_extra_first_GetUserFavoriteCountRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_douyin_extra_first_GetUserFavoriteCountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_GetUserFavoriteCountRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_douyin_extra_first_GetFavoriteCountResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_douyin_extra_first_GetFavoriteCountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_douyin_extra_first_GetFavoriteCountResponse_descriptor,
        new java.lang.String[] { "FavoriteCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
