// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite.proto

package com.xty.dubbo_gen.favorite;

public interface FavoriteListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.extra.first.FavoriteListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 调用者id
   * </pre>
   *
   * <code>int64 from_user_id = 1;</code>
   * @return The fromUserId.
   */
  long getFromUserId();

  /**
   * <pre>
   * 被调用者id
   * </pre>
   *
   * <code>int64 to_user_id = 2;</code>
   * @return The toUserId.
   */
  long getToUserId();
}
