// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite.proto

package com.xty.dubbo_gen.favorite;

/**
 * Protobuf type {@code douyin.extra.first.FavoriteActionRequest}
 */
public final class FavoriteActionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:douyin.extra.first.FavoriteActionRequest)
    FavoriteActionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FavoriteActionRequest.newBuilder() to construct.
  private FavoriteActionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FavoriteActionRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FavoriteActionRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xty.dubbo_gen.favorite.FavoriteServiceProto.internal_static_douyin_extra_first_FavoriteActionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xty.dubbo_gen.favorite.FavoriteServiceProto.internal_static_douyin_extra_first_FavoriteActionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xty.dubbo_gen.favorite.FavoriteActionRequest.class, com.xty.dubbo_gen.favorite.FavoriteActionRequest.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  private long userId_ = 0L;
  /**
   * <pre>
   * 用户鉴权token
   * </pre>
   *
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int VIDEO_ID_FIELD_NUMBER = 2;
  private long videoId_ = 0L;
  /**
   * <pre>
   * 视频id
   * </pre>
   *
   * <code>int64 video_id = 2;</code>
   * @return The videoId.
   */
  @java.lang.Override
  public long getVideoId() {
    return videoId_;
  }

  public static final int ACTION_TYPE_FIELD_NUMBER = 3;
  private int actionType_ = 0;
  /**
   * <pre>
   * 1-点赞，2-取消点赞
   * </pre>
   *
   * <code>int32 action_type = 3;</code>
   * @return The actionType.
   */
  @java.lang.Override
  public int getActionType() {
    return actionType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (videoId_ != 0L) {
      output.writeInt64(2, videoId_);
    }
    if (actionType_ != 0) {
      output.writeInt32(3, actionType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (videoId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, videoId_);
    }
    if (actionType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, actionType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xty.dubbo_gen.favorite.FavoriteActionRequest)) {
      return super.equals(obj);
    }
    com.xty.dubbo_gen.favorite.FavoriteActionRequest other = (com.xty.dubbo_gen.favorite.FavoriteActionRequest) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (getVideoId()
        != other.getVideoId()) return false;
    if (getActionType()
        != other.getActionType()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + VIDEO_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVideoId());
    hash = (37 * hash) + ACTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getActionType();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xty.dubbo_gen.favorite.FavoriteActionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code douyin.extra.first.FavoriteActionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:douyin.extra.first.FavoriteActionRequest)
      com.xty.dubbo_gen.favorite.FavoriteActionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xty.dubbo_gen.favorite.FavoriteServiceProto.internal_static_douyin_extra_first_FavoriteActionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xty.dubbo_gen.favorite.FavoriteServiceProto.internal_static_douyin_extra_first_FavoriteActionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xty.dubbo_gen.favorite.FavoriteActionRequest.class, com.xty.dubbo_gen.favorite.FavoriteActionRequest.Builder.class);
    }

    // Construct using com.xty.dubbo_gen.favorite.FavoriteActionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0L;
      videoId_ = 0L;
      actionType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xty.dubbo_gen.favorite.FavoriteServiceProto.internal_static_douyin_extra_first_FavoriteActionRequest_descriptor;
    }

    @java.lang.Override
    public com.xty.dubbo_gen.favorite.FavoriteActionRequest getDefaultInstanceForType() {
      return com.xty.dubbo_gen.favorite.FavoriteActionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.xty.dubbo_gen.favorite.FavoriteActionRequest build() {
      com.xty.dubbo_gen.favorite.FavoriteActionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xty.dubbo_gen.favorite.FavoriteActionRequest buildPartial() {
      com.xty.dubbo_gen.favorite.FavoriteActionRequest result = new com.xty.dubbo_gen.favorite.FavoriteActionRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xty.dubbo_gen.favorite.FavoriteActionRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.videoId_ = videoId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.actionType_ = actionType_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xty.dubbo_gen.favorite.FavoriteActionRequest) {
        return mergeFrom((com.xty.dubbo_gen.favorite.FavoriteActionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xty.dubbo_gen.favorite.FavoriteActionRequest other) {
      if (other == com.xty.dubbo_gen.favorite.FavoriteActionRequest.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getVideoId() != 0L) {
        setVideoId(other.getVideoId());
      }
      if (other.getActionType() != 0) {
        setActionType(other.getActionType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              videoId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              actionType_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <pre>
     * 用户鉴权token
     * </pre>
     *
     * <code>int64 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * 用户鉴权token
     * </pre>
     *
     * <code>int64 user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户鉴权token
     * </pre>
     *
     * <code>int64 user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long videoId_ ;
    /**
     * <pre>
     * 视频id
     * </pre>
     *
     * <code>int64 video_id = 2;</code>
     * @return The videoId.
     */
    @java.lang.Override
    public long getVideoId() {
      return videoId_;
    }
    /**
     * <pre>
     * 视频id
     * </pre>
     *
     * <code>int64 video_id = 2;</code>
     * @param value The videoId to set.
     * @return This builder for chaining.
     */
    public Builder setVideoId(long value) {

      videoId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 视频id
     * </pre>
     *
     * <code>int64 video_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideoId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      videoId_ = 0L;
      onChanged();
      return this;
    }

    private int actionType_ ;
    /**
     * <pre>
     * 1-点赞，2-取消点赞
     * </pre>
     *
     * <code>int32 action_type = 3;</code>
     * @return The actionType.
     */
    @java.lang.Override
    public int getActionType() {
      return actionType_;
    }
    /**
     * <pre>
     * 1-点赞，2-取消点赞
     * </pre>
     *
     * <code>int32 action_type = 3;</code>
     * @param value The actionType to set.
     * @return This builder for chaining.
     */
    public Builder setActionType(int value) {

      actionType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1-点赞，2-取消点赞
     * </pre>
     *
     * <code>int32 action_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearActionType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      actionType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:douyin.extra.first.FavoriteActionRequest)
  }

  // @@protoc_insertion_point(class_scope:douyin.extra.first.FavoriteActionRequest)
  private static final com.xty.dubbo_gen.favorite.FavoriteActionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xty.dubbo_gen.favorite.FavoriteActionRequest();
  }

  public static com.xty.dubbo_gen.favorite.FavoriteActionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FavoriteActionRequest>
      PARSER = new com.google.protobuf.AbstractParser<FavoriteActionRequest>() {
    @java.lang.Override
    public FavoriteActionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FavoriteActionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FavoriteActionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xty.dubbo_gen.favorite.FavoriteActionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

