// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite.proto

package com.xty.dubbo_gen.favorite;

public interface GetFavoriteCountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.extra.first.GetFavoriteCountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 favorite_count = 1;</code>
   * @return The favoriteCount.
   */
  long getFavoriteCount();
}
