// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite.proto

package com.xty.dubbo_gen.favorite;

public interface GetUserFavoriteCountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.extra.first.GetUserFavoriteCountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
