// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite.proto

package com.xty.dubbo_gen.favorite;

public interface GetVideoFavoriteCountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.extra.first.GetVideoFavoriteCountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 video_id = 1;</code>
   * @return The videoId.
   */
  long getVideoId();
}
