// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite.proto

package com.xty.dubbo_gen.favorite;

public interface IsUserFavoriteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.extra.first.IsUserFavoriteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 video_id = 2;</code>
   * @return The videoId.
   */
  long getVideoId();
}
