// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite.proto

package com.xty.dubbo_gen.favorite;

public interface IsUserFavoriteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.extra.first.IsUserFavoriteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_favorite = 1;</code>
   * @return The isFavorite.
   */
  boolean getIsFavorite();
}
