// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: favorite.proto

package com.xty.dubbo_gen.favorite;

public interface VideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:douyin.extra.first.Video)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 视频唯一标识
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   * 视频作者信息
   * </pre>
   *
   * <code>.douyin.extra.first.User author = 2;</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <pre>
   * 视频作者信息
   * </pre>
   *
   * <code>.douyin.extra.first.User author = 2;</code>
   * @return The author.
   */
  com.xty.dubbo_gen.favorite.User getAuthor();
  /**
   * <pre>
   * 视频作者信息
   * </pre>
   *
   * <code>.douyin.extra.first.User author = 2;</code>
   */
  com.xty.dubbo_gen.favorite.UserOrBuilder getAuthorOrBuilder();

  /**
   * <pre>
   * 视频播放地址
   * </pre>
   *
   * <code>string play_url = 3;</code>
   * @return The playUrl.
   */
  java.lang.String getPlayUrl();
  /**
   * <pre>
   * 视频播放地址
   * </pre>
   *
   * <code>string play_url = 3;</code>
   * @return The bytes for playUrl.
   */
  com.google.protobuf.ByteString
      getPlayUrlBytes();

  /**
   * <pre>
   * 视频封面地址
   * </pre>
   *
   * <code>string cover_url = 4;</code>
   * @return The coverUrl.
   */
  java.lang.String getCoverUrl();
  /**
   * <pre>
   * 视频封面地址
   * </pre>
   *
   * <code>string cover_url = 4;</code>
   * @return The bytes for coverUrl.
   */
  com.google.protobuf.ByteString
      getCoverUrlBytes();

  /**
   * <pre>
   * 视频的点赞总数
   * </pre>
   *
   * <code>int64 favorite_count = 5;</code>
   * @return The favoriteCount.
   */
  long getFavoriteCount();

  /**
   * <pre>
   * 视频的评论总数
   * </pre>
   *
   * <code>int64 comment_count = 6;</code>
   * @return The commentCount.
   */
  long getCommentCount();

  /**
   * <pre>
   * true-已点赞，false-未点赞
   * </pre>
   *
   * <code>bool is_favorite = 7;</code>
   * @return The isFavorite.
   */
  boolean getIsFavorite();

  /**
   * <pre>
   * 视频标题
   * </pre>
   *
   * <code>string title = 8;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * 视频标题
   * </pre>
   *
   * <code>string title = 8;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
